### ISSUE TITLE
Maximum Zip Size for All Browsers

### ISSUE THREAD

**Issue by sifex** [textileio/textile-facebook#2]
Hey, 

One issue I've faced is that browsers don't like it when you drag a 3GB zip onto them. Not sure exactly what the file size is, but most of it was messenger data.

Might add a disclaimer as a PR to the project.

**Comment by sifex** [comment]
Solution seems to be to zip the contents of the extracted folder, not the folder it creates. Doesn't seem to be any way around this as FF/Chrome full tab-crash.

**Comment by andrewxhill** [comment]
thanks for the pr, super. i minimized it's immediate impact on the minimal design by just making it expandable. thanks again
