### ISSUE TITLE
Need more lenient mimetype check

### ISSUE THREAD

**Issue by jessicah** [textileio/textile-facebook#4]
https://github.com/textileio/textile-facebook/blob/600d797be59828a6d49469cc4baef9361cd86689/js/app.js#L28

On a Windows 10 machine with both Chrome & Edge, this didn't work, as the mimetype reported is `application/x-zip-compressed`

**Comment by andrewxhill** [comment]
thanks for the note. i just pushed a blind fix, can you give the latest a try?

**Comment by jessicah** [comment]
Works :)
